#!/bin/bash
VERSION=`grep '"version"' manifest.json | cut -d '"' -f 4`
ZPATH="versions"
ZIPPATH="$ZPATH/$VERSION.zip"
CRX="$ZPATH/$VERSION.crx"
KEY="$ZPATH/key.pem"
mkdir -pv "./$ZPATH"
rm -rfv "$ZIPPATH"
find . -name "*" -not -path "./.*" -not -path "./versions*" -print | zip -9 -X "$ZIPPATH" -@
echo "Zip created: ./$ZIPPATH"


#building crx
pub="$VERSION.pub"
sig="$VERSION.sig"
trap 'rm -f "$pub" "$sig"' EXIT

# signature
openssl sha1 -sha1 -binary -sign "$KEY" < "$ZIPPATH" > "$sig"

# public key
openssl rsa -pubout -outform DER < "$KEY" > "$pub" 2>/dev/null

byte_swap () {
  # Take "abcdefgh" and return it as "ghefcdab"
  echo "${1:6:2}${1:4:2}${1:2:2}${1:0:2}"
}

crmagic_hex="4372 3234" # Cr24
version_hex="0200 0000" # 2
pub_len_hex=$(byte_swap $(printf '%08x\n' $(ls -l "$pub" | awk '{print $5}')))
sig_len_hex=$(byte_swap $(printf '%08x\n' $(ls -l "$sig" | awk '{print $5}')))
(
  echo "$crmagic_hex $version_hex $pub_len_hex $sig_len_hex" | xxd -r -p
  cat "$pub" "$sig" "$ZIPPATH"
) > "$CRX"
echo "crx created: ./$CRX"
