#!/bin/bash
VERSION=`grep '"version"' manifest.json | cut -d '"' -f 4`
ZPATH="versions"
ZIPPATH="$ZPATH/$VERSION.zip"
mkdir -pv "./$ZPATH"
rm -rfv "$ZIPPATH"
find . -name "*" -not -path "./.*" -not -path "./versions*" -print | zip "$ZIPPATH" -@
echo "Zip created: ./$ZIPPATH"
